POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "WebClient Doe",
  "email": "webclient@email.com",
  "address": "123, address street",
  "dateOfBirth": "1999-01-01",
  "registeredDate": "2025-10-10"
}